# Install script for divemarkus
# Version 08282025-0245
# You can download this script and execute on PowerShell
# https://chocolatey.org/packages

ECHO Installing apps

ECHO Configure chocolatey
choco feature enable -n allowGlobalConfirmation

choco install 7zip.install
choco install adobereader
choco install amazon-music
choco install bind-toolsonly
choco install bitwarden
choco install brave
choco install crystaldiskmark
choco install cpu-z
choco install curl
choco install discord
choco install drawio
choco install everything
choco install ffmpeg
choco install firefox
choco install foobar2000
choco install geforce-experience
choco install googlechrome
choco install googleearth
choco install git.install
choco install github
choco install gpu-z
choco install hwmonitor
choco install iperf3
choco install irfanview
choco install keepassxc
choco install kodi
choco install mullvad-app
choco install nmap
choco install notepadplusplus.install
choco install nvidia-display-driver
choco install openhardwaremonitor
choco install osquery
choco install paint.net
choco install powertoys
choco install pstools
choco install putty
choco install sharex
choco install speedtest
choco install steam
choco install sysinternals
choco install veracrypt
choco install vscode
choco install vlc
choco install wget
choco install whois
choco install windirstat
choco install winscp
choco install wireshark
choco install yt-dlp

# MISC on queue
#choco install advanced-ip-scanner
#choco install aida64extreme
#choco install anaconda3
#choco install android-sdk
#choco install audacity
#choco install autohotkey.portable
#choco install autoruns
#choco install avgantivirusfree
#choco install baretail
#choco install bginfo
#choco install chromium
#choco install classic-shell
#choco install cmder
#choco install consolez
#choco install couchpotato
#choco install cygwin
#choco install dbeaver
#choco install docker
#choco install elasticsearch
#choco install etcher
#choco install fakenet
#choco install filebeat
#choco install filezilla
#choco install googledrive
#choco install graphviz
#choco install heidisql
#choco install hugin.install
#choco install imagemagick
#choco install irfanviewplugins
#choco install keepassx
#choco install kibana
#choco install k-litecodecpackfull
#choco install kubernetes-cli
#choco install kubernetes-helm
#choco install libreoffice-fresh
#choco install linqpad4 
#choco install makemkv
#choco install mobaxterm
#choco install msiafterburner
#choco install mysql.workbench
#choco install nugetpackageexplorer
#choco install obs-studio
#choco install openssh
#choco install openssl.light
#choco install picasa
#choco install pgadmin4
#choco install popcorntime
#choco install powerbi
#choco install poweriso
#choco install plexmediaserver
#choco install python.cheetah
#choco install qutebrowser.install
#choco install rdcman
#choco install royalts
#choco install rufus.portable
#choco install sabnzbd
#choco install sdformatter
#choco install sickbeard
#choco install signal
#choco install selenium-all-drivers
#choco install spotify
#choco install sql-server-management-studio
#choco install teracopy
#choco install tor-browser
#choco install totalcommander
#choco install unetbootin
#choco install vifm
#choco install virtualclonedrive
#choco install virtualbox
#choco install virtualbox.extensionpack
#choco install vivaldi
#choco install vmwarevsphereclient
#choco install windowsrepair
#choco install winget-cli
#choco install winlogbeat
#choco install winpcap
#choco install winrar
#choco install wnetwatcher.install
#choco install wps-office-free
#choco install yumi
#choco install awscli
#choco install ChocolateyGUI
#choco install fiddler
#choco install gimp
#choco install kindle

choco feature disable -n allowGlobalConfirmation
